

name: CI

on:

  push:
    branches: [ master ]

jobs:

  build1:
    
    runs-on: windows-latest
    steps:

      - uses: actions/checkout@v3

      - name: build-win
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
          cmake --build . --config Release
          cpack -C Release
          cpack -G NSIS64
          
  build2:
    
    runs-on: macos-latest
    steps:
        - uses: actions/checkout@v3
        - name: build-mac
          run: |
            mkdir build
            cd build
            cmake ..
            cmake --build .
            cpack -G DragNDrop
  build3:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3


      - name: set
        run: sudo apt install cmake rpm g++
      
      - name: build-linux
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
          cpack -G DEB
          cpack -G RPM
          
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false 
